FROM golang:1.7-alpine

COPY . /go/src/github.com/djmaze/docker-volume-ceph-rbd
WORKDIR /go/src/github.com/djmaze/docker-volume-ceph-rbd

RUN set -ex \
    && apk add --no-cache --virtual .build-deps \
    gcc libc-dev \
    && go install --ldflags '-extldflags "-static"' \
    && apk del .build-deps

CMD ["/go/bin/docker-volume-ceph-rbd"]
